Currently Loaded Modulefiles:
  1) gcc-libs/4.9.2                   13) giflib/5.1.1
  2) cmake/3.21.1                     14) emacs/28.1
  3) flex/2.5.39                      15) tmux/3.2a
  4) git/2.32.0                       16) mrxvt/0.5.4
  5) apr/1.7.0                        17) userscripts/1.4.0
  6) apr-util/1.6.1                   18) rcps-core/1.0.0
  7) subversion/1.14.1                19) default-modules/2018
  8) screen/4.8.0-ucl1                20) compilers/gnu/4.9.2
  9) gerun                            21) cuda/10.1.243/gnu-4.9.2
 10) nano/2.4.2                       22) python/3.8.6
 11) nedit/5.6-aug15                  23) openblas/0.3.7-serial/gnu-4.9.2
 12) dos2unix/7.3                     24) python3/3.8
/lustre/home/zceccgr/spkenv2/lib/python3.8/site-packages/spikeinterface/sorters/waveclus/waveclus.py:124: ResourceWarning: unclosed file <_io.TextIOWrapper name=4 encoding='UTF-8'>
  if cls.check_compiled():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
2022-09-18 14:11:32 INFO     Starting
2022-09-18 14:11:32 INFO     at main function
2022-09-18 14:11:32 INFO     variable: BlockNellie-115
Traceback (most recent call last):
  File "/home/zceccgr/Scratch/zceccgr/spikeinterface3cg/interfacetest_jules_cg_kilosort_concatenate_ms4_reducchan2.py", line 247, in <module>
    main()
  File "/home/zceccgr/Scratch/zceccgr/spikeinterface3cg/interfacetest_jules_cg_kilosort_concatenate_ms4_reducchan2.py", line 211, in main
    new_data = preprocess_data_cg(data)
  File "/home/zceccgr/Scratch/zceccgr/spikeinterface3cg/interfacetest_jules_cg_kilosort_concatenate_ms4_reducchan2.py", line 131, in preprocess_data_cg
    recording = recording.set_probe(probe)
  File "/lustre/home/zceccgr/spkenv2/lib/python3.8/site-packages/spikeinterface/core/baserecording.py", line 338, in set_probe
    return self.set_probes(probegroup, group_mode=group_mode, in_place=in_place)
  File "/lustre/home/zceccgr/spkenv2/lib/python3.8/site-packages/spikeinterface/core/baserecording.py", line 392, in set_probes
    arr = probegroup.to_numpy(complete=True)
  File "/lustre/home/zceccgr/spkenv2/lib/python3.8/site-packages/probeinterface/probegroup.py", line 62, in to_numpy
    arr = probe.to_numpy(complete=complete)
  File "/lustre/home/zceccgr/spkenv2/lib/python3.8/site-packages/probeinterface/probe.py", line 720, in to_numpy
    arr['device_channel_indices'] = self.device_channel_indices
ValueError: could not broadcast input array from shape (12,) into shape (32,)
tar: Removing leading `/' from member names
